version: '3'

services:
  web1:
    container_name: "sugar-web1"
    image: php82_web
    build: images/php/82/apache
    ports:
      - "80:80"
    environment:
      - "APACHE_RUN_USER=sugar"
      - "APACHE_RUN_GROUP=sugar"
    volumes:
      - ../data:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
      - permissions
      - redis
    links:
      - mysql
      - elasticsearch
      - redis
  cron:
    container_name: "sugar-cron"
    image: php82_web_cron
    build: images/php/82/cron
    volumes:
      - ../data:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
      - permissions
      - redis
    links:
      - mysql
      - elasticsearch
      - redis
  mysql:
    container_name: "sugar-mysql"
    image: sugar_mysql80
    build: images/mysql/80
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sugar
      - MYSQL_PASSWORD=sugar
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: "sugar-elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../elasticsearch:/usr/share/elasticsearch/data
    environment:
      - node.name=sugar1
      - cluster.name=sugarcrm79
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  redis:
    container_name: "sugar-redis"
    image: redis:latest
    volumes:
      - ../redis:/data
  permissions:
    container_name: "sugar-permissions"
    image: esimonetti/sugardockerized:permissions-1.19
    volumes:
      - ../data:/var/www/html